# Site Settings
baseurl: 		""
title: 		CoderOnCode

name: 			Coder<strong>On</strong>Code
description: Random ramblings about code, programming, and technology
url: 			"http://coderoncode.com"

paginate: 		10
paginate_path: 	"blog/page:num"
destination: 	/srv/www/coderoncode.com/public_html
excerpt_separator: "-=excerpt=-"
post_ext: md


twitter: 		allanmacgregor
email: 			dev@allanmacgregor.com

disqus: 		codercode
analytics: 		UA-28450068-1

copyright: 		Copyright 2014-2015 CoderOnCode.com

# Build Settings
permalinks: 	pretty
