#!/bin/sh
export JEKYLL_ENV='production'

# Remove the contents of the _site folder 
rm -Rf _site/*

# Generate the site in case it wasn't generated 
jekyll build --lsi

# Upload to server
#scp -r _site/* st1.am.com:/srv/www/coderoncode.com/public_html
#scp -r _site/* st2.am.com:/srv/www/coderoncode.com/public_html
#rsync -rave ssh _site/* st1.am.com:/srv/www/coderoncode.com/public_html
#rsync -rave ssh _site/* st2.am.com:/srv/www/coderoncode.com/public_html
#rsync -rave ssh _site/* web1.static:/srv/www/coderoncode.com/public_html
rsync -rave ssh _site/* web3.static:/srv/www/coderoncode.com/public_html
